export const COLLECTION_LISTS = [
    {
        id: 1,
        category: 'art',
        title: 'Explore Art',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/kVVevhk9BBE5BSuIoQfkH5_5FVsPTJCR34wpVBf1ACURh9dfNaybChPgiicte10yb6SYVp5iMQNXaQrOnHXmRiiOtVxUzYJR3M1I=h600',
    },
    {
        id: 2,
        category: 'boats',
        title: 'Explore Boats',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/QL_soNRHBsOZYwXLEFZXhiL1WgRwsOiy3RSqAREAcl9bMxA482wbVJOVtHrqe-swaJh66bnA0mjeAlj81UkDmwVyJyVVlD1aZWXdRw=h600',
    },
    {
        id: 3,
        category: 'cars',
        title: 'Explore Cars',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/8VGubP7xBfRaeO_EslP8yXVyI0sMyfysOnt1NfbBnY6O7djIVrMeCXHZ8Y2hDqu6DEEc7UZqf87CcxxEOlgVDcVG1TTT72KLpi4_G9M=h600',
    },
    {
        id: 4,
        category: 'fashion',
        title: 'Explore Fashion',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/RcGxoyj3tySVAERjyOY1NkzHqxMoHjwsfeKNHAzRFflgXynRAnK8Iwnp-uY-cYF370FAXcud0UKb0QxTlgWD73U3pQSIgUwOtyA2=h600',
    },
    {
        id: 5,
        category: 'jewelry',
        title: 'Explore Jewelry',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/QL_soNRHBsOZYwXLEFZXhiL1WgRwsOiy3RSqAREAcl9bMxA482wbVJOVtHrqe-swaJh66bnA0mjeAlj81UkDmwVyJyVVlD1aZWXdRw=h600',
    },
    {
        id: 6,
        category: 'planes',
        title: 'Explore Planes',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/5-KeOMqOlfC7D6etYVEcrEiPcRy_QB-KPS3uOeGu7hMsPorzvPNtJOVrQRb1rxjHFcFsyXEQmTdj7bvqlbAQD5foHQxbTEgb5GPaMLg=h600',
    },
    {
        id: 7,
        category: 'realEstate',
        title: 'Explore Real Estate',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/S6D3GIB6cMOW1U_n9_zN5qegkR-X-zb-Z5dnpkMABKo1UzROM8dDgw1l7PGL2oe-En4OsF_3IOUa3cRVcfYGkC8rW-lhXRY2Iv5sQQ=h600',
    },
    {
        id: 8,
        category: 'watches',
        title: 'Explore Watches',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/iWzbt-MmKEaNvcUcSXIuruMvQjMYQT8DcIoed6pPzIHJfggCtoevFceutlAxZmS3RXwqBF_zIthsJ9_5FRK-p88r9CezqFnRC0fncQ=h600',
    },
    {
        id: 9,
        category: 'wine',
        title: 'Explore Wine',
        description: 'An online community of makers, developers, and traders is pushing the art world into new territory. It all started with CryptoPunks, a set of 10,000 randomly generated punks that proved demand for the digital ownership of non-physical items and collectibles in 2017, and the market has evolved rapidly ever since.',
        banner: 'https://lh3.googleusercontent.com/Nb4x0jbUjYoETXfaeECLa6YAZTjluINrTETkoU_VRklO1aAUTCmwUmttydJlGOkcroQFWrcdU3P9g1IbaI9h2wWPR3k_vWrpS-8G=h600',
    },
]