export const NEW_ITMES = [
    {
        title: 'Hello NFT',
        avatar_url: '/img/author/author-5.jpg',
        preview_image_url: '/img/items/static-1.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    },
    {
        title: 'Hello NFT',
        deadline: '2022-01-30T15:41:46.404Z',
        avatar_url: '/img/author/author-1.jpg',
        preview_image_url: '/img/items/static-3.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    },
    {
        title: 'Hello NFT',
        avatar_url: '/img/author/author-3.jpg',
        preview_image_url: '/img/items/static-2.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    },
    {
        title: 'Hello NFT',
        deadline: '2022-01-30T15:41:46.404Z',
        avatar_url: '/img/author/author-2.jpg',
        preview_image_url: '/img/items/static-4.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    },
    {
        title: 'Hello NFT',
        deadline: '2022-01-30T15:41:46.404Z',
        avatar_url: '/img/author/author-4.jpg',
        preview_image_url: '/img/items/static-6.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    },
    {
        title: 'Hello NFT',
        avatar_url: '/img/author/author-5.jpg',
        preview_image_url: '/img/items/static-5.jpg',
        bid_link: '',
        max_bid: '12',
        bid: '4',
        likes: '10',
    }
]